(function(g){var window=this;var x5=function(a,b,c){var d=b.bc();g.U(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.jd(c?c:"mqdefault.jpg");var f=b instanceof g.UO&&b.lengthSeconds?g.eV(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.xQ(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.UO?b.La:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.Wl||g.lX("\u0645\u0634\u0627\u0647\u062f\u0629 $TITLE",{TITLE:b.title}),duration:f,
url:b.Lm(),is_live:l,is_list:k,is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.zQ&&(d.playlist_length=b.getLength());a.update(d)},y5=function(a,b){g.SH.call(this,{I:"div",
fa:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},z5=function(a){g.W.call(this,{I:"div",
M:"ytp-upnext",U:{"aria-label":"{{aria_label}}"},P:[{I:"div",M:"ytp-cued-thumbnail-overlay-image",U:{style:"{{background}}"}},{I:"span",M:"ytp-upnext-top",P:[{I:"span",M:"ytp-upnext-header",ca:"\u0627\u0644\u062a\u0627\u0644\u064a"},{I:"span",M:"ytp-upnext-title",ca:"{{title}}"},{I:"span",M:"ytp-upnext-author",ca:"{{author}}"}]},{I:"a",M:"ytp-upnext-autoplay-icon",U:{role:"button",href:"{{url}}","aria-label":"\u062a\u0634\u063a\u064a\u0644 \u0627\u0644\u0641\u064a\u062f\u064a\u0648 \u0627\u0644\u062a\u0627\u0644\u064a"},
P:[{I:"svg",U:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},P:[{I:"circle",M:"ytp-svg-autoplay-circle",U:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",M:"ytp-svg-autoplay-ring",U:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",M:"ytp-svg-fill",U:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",M:"ytp-upnext-bottom",
P:[{I:"span",M:"ytp-upnext-cancel"},{I:"span",M:"ytp-upnext-paused",ca:"\u062a\u0645 \u0625\u064a\u0642\u0627\u0641 \u0627\u0644\u062a\u0634\u063a\u064a\u0644 \u0627\u0644\u062a\u0644\u0642\u0627\u0626\u064a \u0645\u0624\u0642\u062a\u064b\u0627"}]}]});this.F=null;var b=this.o["ytp-upnext-cancel"];this.F=new g.W({I:"button",fa:["ytp-upnext-cancel-button","ytp-button"],U:{tabindex:"0","aria-label":"\u0625\u0644\u063a\u0627\u0621 \u0627\u0644\u062a\u0634\u063a\u064a\u0644 \u0627\u0644\u062a\u0644\u0642\u0627\u0626\u064a"},
ca:"\u0625\u0644\u063a\u0627\u0621"});g.N(this,this.F);this.F.W("click",this.BS,this);this.F.xa(b);this.B=a;this.L=this.o["ytp-svg-autoplay-ring"];this.H=this.G=this.C=this.D=null;this.J=new g.V(this.So,5E3,this);g.N(this,this.J);this.K=0;this.R(this.o["ytp-upnext-autoplay-icon"],"click",this.NU);this.iE();this.R(a,"autonavvisibility",this.iE);this.R(a,"mdxnowautoplaying",this.eU);this.R(a,"mdxautoplaycanceled",this.fU);this.R(a,"mdxautoplayupnext",this.VG);3==this.B.Sa()&&(a=(a=g.aU(g.TT(this.B)))?
a.CL():null)&&this.VG(a)},A5=function(a,b){if(!a.C){g.fG("a11y-announce","\u0627\u0644\u062a\u0627\u0644\u064a "+a.D.title);
a.K=g.qG();a.C=new g.V((0,g.B)(a.Js,a,b),25);a.Js(b);var c=b||g.Y(a.B).experiments.A("autoplay_time")||1E4;a.B.ya("onAutonavCoundownStarted",c)}g.Eq(a.element,"ytp-upnext-autoplay-paused")},C5=function(a){B5(a);
a.K=g.qG();a.Js();g.T(a.element,"ytp-upnext-autoplay-paused")},B5=function(a){a.C&&(a.C.dispose(),a.C=null)},D5=function(a,b){b=void 0===b?!1:b;
if(g.Y(a.B).experiments.o("autonav_notifications")&&b&&window.Notification&&window.document.hasFocus){var c=window.Notification.permission;"default"==c?window.Notification.requestPermission():"granted"!=c||window.document.hasFocus()||(c=a.D.bc(),a.So(),a.G=new window.Notification("\u0627\u0644\u062a\u0627\u0644\u064a",{body:c.title,icon:c.jd()}),a.H=a.R(a.G,"click",a.DU),a.J.start())}B5(a);a.B.Zk(!1,b)},HCa=function(a){y5.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.B=new g.W({I:"div",M:"ytp-subscribe-card",P:[{I:"img",M:"ytp-author-image",U:{src:b.profilePicture}},{I:"div",M:"ytp-subscribe-card-right",P:[{I:"div",M:"ytp-author-name",ca:b.author},{I:"div",M:"html5-subscribe-button-container"}]}]});g.N(this,this.B);this.B.xa(this.element);this.C=new g.NZ("\u0627\u0644\u0627\u0634\u062a\u0631\u0627\u0643",null,"\u0625\u0644\u063a\u0627\u0621 \u0627\u0644\u0627\u0634\u062a\u0631\u0627\u0643",null,!0,!1,b.Il,b.subscribed,"trailer-endscreen",
null,null,a);g.N(this,this.C);this.C.xa(this.B.o["html5-subscribe-button-container"]);this.hide()},E5=function(a){var b=g.Y(a),c=g.EI||g.pf?{style:"will-change: opacity"}:void 0,d=b.o,e=["ytp-videowall-still"];
b.B&&e.push("ytp-videowall-show-text");g.W.call(this,{I:"a",fa:e,U:{href:"{{url}}",target:d?"_blank":"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},P:[{I:"div",M:"ytp-videowall-still-image",U:{style:"{{background}}"}},{I:"span",M:"ytp-videowall-still-info",P:[{I:"span",M:"ytp-videowall-still-info-bg",P:[{I:"span",M:"ytp-videowall-still-info-content",U:c,P:[{I:"span",M:"ytp-videowall-still-info-title",ca:"{{title}}"},{I:"span",
M:"ytp-videowall-still-info-author",ca:"{{author_and_views}}"},{I:"span",M:"ytp-videowall-still-info-live",ca:"\u0645\u0628\u0627\u0634\u0631"},{I:"span",M:"ytp-videowall-still-info-duration",ca:"{{duration}}"}]}]}]},{I:"span",fa:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],P:[{I:"span",M:"ytp-videowall-still-listlabel-icon"},"\u0642\u0627\u0626\u0645\u0629 \u062a\u0634\u063a\u064a\u0644",{I:"span",M:"ytp-videowall-still-listlabel-length",P:[" (",{I:"span",ca:"{{playlist_length}}"},
")"]}]},{I:"span",fa:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],P:[{I:"span",M:"ytp-videowall-still-listlabel-mix-icon"},"\u062a\u0634\u0643\u064a\u0644\u0629",{I:"span",M:"ytp-videowall-still-listlabel-length",ca:" (50+)"}]}]});this.F=d;this.B=a;this.C=null;this.D=new g.PF(this);g.N(this,this.D);this.W("click",this.H);this.W("keypress",this.J);this.D.R(a,"videodatachange",this.G);g.Y(a).X&&(a=a.app.ma,b=this.element,g.Ma(a.o,b),g.Pa(a.o,b),c=String(a.K++),b.setAttribute("data-visual-id",
c),g.jf(this,(0,g.B)(a.J,a,b)));this.G()},F5=function(a){y5.call(this,a,"videowall-endscreen");
this.K=a;this.G=0;this.C=[];this.H=this.F=this.D=null;this.J=this.O=!1;this.Z=new g.PF(this);g.N(this,this.Z);this.L=new g.V(g.Da(g.T,this.element,"ytp-show-tiles"),0);g.N(this,this.L);var b=new g.W({I:"button",fa:["ytp-button","ytp-endscreen-previous"],U:{"aria-label":"\u0627\u0644\u0633\u0627\u0628\u0642"},P:[g.YU()]});g.N(this,b);b.xa(this.element);b.W("click",this.BQ,this);this.N=new g.MH({I:"div",M:"ytp-endscreen-content"});g.N(this,this.N);this.N.xa(this.element);b=new g.W({I:"button",fa:["ytp-button",
"ytp-endscreen-next"],U:{"aria-label":"\u0627\u0644\u062a\u0627\u0644\u064a"},P:[g.ZU()]});g.N(this,b);b.xa(this.element);b.W("click",this.AQ,this);this.B=new z5(a);g.N(this,this.B);g.tU(this.player,this.B.element,4);this.hide()},G5=function(a){return g.vU(a.player)&&a.wz()&&!a.H},ICa=function(a,b){return(0,g.I)(b.suggestions,function(b){b=g.HX(g.Y(a.K),b);
g.N(a,b);return b})},H5=function(a){var b=a.Nv();
b!=a.O&&(a.O=b,a.player.V("autonavvisibility"))},I5=function(a){g.FU.call(this,a);
this.o=null;this.A=new g.PF(this);g.N(this,this.A);this.B=g.Y(a);JCa(a)?this.o=new F5(this.player):this.B.Fa?this.o=new HCa(this.player):this.o=new y5(this.player);g.N(this,this.o);g.tU(this.player,this.o.element,4);this.DF();this.A.R(a,"videodatachange",this.DF,this);this.A.R(a,"crn_endscreen",this.BO,this);this.A.R(a,"crx_endscreen",this.CO,this)},JCa=function(a){a=g.Y(a);
return a.Wc&&!a.Fa};
g.t(y5,g.SH);y5.prototype.create=function(){this.created=!0};
y5.prototype.destroy=function(){this.created=!1};
y5.prototype.wz=function(){return!1};
y5.prototype.Nv=function(){return!1};g.t(z5,g.W);g.h=z5.prototype;g.h.So=function(){this.G&&(this.J.stop(),this.Ha(this.H),this.H=null,this.G.close(),this.G=null)};
g.h.iE=function(){g.RH(this,g.UT(this.B))};
g.h.DU=function(){window.focus();this.So()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.Js=function(a){a=a||g.Y(this.B).experiments.A("autoplay_time")||1E4;var b=Math.min(g.qG()-this.K,a);a=Math.min(b/a,1);this.L.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.B.Sa()?D5(this,!0):this.C&&this.C.start()};
g.h.NU=function(a){!g.Zd(this.F.element,g.DF(a))&&g.IW(a,this.B)&&D5(this)};
g.h.BS=function(){g.XT(this.B,!0)};
g.h.eU=function(a){this.B.Sa();this.show();A5(this,a)};
g.h.VG=function(a){this.B.Sa();this.D&&this.D.bc().videoId==a.bc().videoId||(this.D=a,x5(this,a,"hqdefault.jpg"))};
g.h.fU=function(){this.B.Sa();B5(this);this.hide()};
g.h.Y=function(){B5(this);this.So();g.W.prototype.Y.call(this)};g.t(HCa,y5);g.t(E5,g.W);E5.prototype.yl=function(){g.yU(this.B,this.element);var a=this.C.bc().videoId,b=this.C.getPlaylistId();g.d0(this.B.app,a,this.C.Hd,b,void 0,void 0,void 0)};
E5.prototype.H=function(a){g.IW(a,this.B,this.F,this.C.Hd||void 0)&&this.yl()};
E5.prototype.J=function(a){switch(a.keyCode){case 13:case 32:g.IF(a)||(this.yl(),g.HF(a))}};
E5.prototype.G=function(){var a=this.B.getVideoData(),b=g.Y(this.B);this.F=a.isDni?!1:b.o};g.t(F5,y5);g.h=F5.prototype;g.h.create=function(){y5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.D=ICa(this,a),this.F=a);this.lh();this.Z.R(this.player,"appresize",this.lh);this.Z.R(this.player,"onVideoAreaChange",this.lh);this.Z.R(this.player,"videodatachange",this.CQ);this.Z.R(this.player,"autonavchange",this.eD);this.Z.R(this.player,"autonavcancel",this.zQ);this.Z.R(this.element,"transitionend",this.fW)};
g.h.destroy=function(){g.RF(this.Z);g.lf(this.C);this.C=[];this.D=null;y5.prototype.destroy.call(this);g.Eq(this.element,"ytp-show-tiles");this.L.stop()};
g.h.wz=function(){return 1!=this.F.autonavState};
g.h.show=function(){y5.prototype.show.call(this);g.Eq(this.element,"ytp-show-tiles");g.Y(this.player).B?g.vu(this.L):this.L.start();(this.J||this.H&&this.H!=this.F.clientPlaybackNonce)&&g.XT(this.player,!1);G5(this)?(H5(this),2==this.F.autonavState?g.Y(this.player).experiments.o("fast_autonav_in_background")&&3==this.player.xj()?D5(this.B,!0):A5(this.B):3==this.F.autonavState&&C5(this.B)):(g.XT(this.player,!0),H5(this))};
g.h.hide=function(){y5.prototype.hide.call(this);C5(this.B);H5(this)};
g.h.fW=function(a){g.DF(a)==this.element&&this.lh()};
g.h.lh=function(){if(this.D&&this.D.length){g.T(this.element,"ytp-endscreen-paginate");var a=g.kU(this.K,!0),b=g.fI(this.K);b&&(b=b.md()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.D.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,r=e/2,v=b<=f-2&&n>=r*m,z=e<=k-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&z)n-=p*m,e+=2;else if(v)n-=r*m,b+=2;else if(z)n-=p*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.ld(a.width/m||1,1,1.21);n*=g.ld(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.N.element;g.Oh(a,m,n);g.wh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.B;f=this.D[0];c.D=f;x5(c,f,"hqdefault.jpg");g.U(this.element,"ytp-endscreen-takeover",G5(this));H5(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,r=0,d&&f>=b-2&&k>=e-
2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),p=g.md(p+this.G,l),0!=r){v=this.C[c];v||(v=new E5(this.player),this.C[c]=v,a.appendChild(v.element));z=Math.floor(n*k/e);var E=Math.floor(m*f/b),J=Math.floor(n*(k+r)/e)-z-4,Q=Math.floor(m*(f+r)/b)-E-4;g.Dh(v.element,E,z);g.Oh(v.element,Q,J);g.wh(v.element,"transitionDelay",(k+f)/20+"s");g.U(v.element,"ytp-videowall-still-mini",1==r);g.U(v.element,"ytp-videowall-still-large",2<r);r=v;p=this.D[p];r.C!=p&&(r.C=p,x5(r,p,g.Cq(r.element,"ytp-videowall-still-large")?
"hqdefault.jpg":"mqdefault.jpg"),v=(p=p.Hd)&&p.itct)&&(p=r.B,g.Y(p).X&&(p=p.app.ma,r=r.element,z=r.getAttribute("data-visual-id"),g.Ma(p.o,r),p.A?v&&(r.visualElement=g.NG(v)):g.wU(p,"onLogServerVeCreated",{id:z,tracking_params:v})));c++}g.U(this.element,"ytp-endscreen-paginate",c<l);for(b=this.C.length-1;b>=c;b--)e=this.C[b],g.Td(e.element),g.kf(e);this.C.length=c}};
g.h.CQ=function(){var a=this.player.getVideoData();this.F!=a&&(this.G=0,this.D=ICa(this,a),this.F=a,this.lh())};
g.h.AQ=function(){this.G+=this.C.length;this.lh()};
g.h.BQ=function(){this.G-=this.C.length;this.lh()};
g.h.FN=function(){return!!this.B.C};
g.h.eD=function(a){1==a?(this.J=!1,this.H=this.F.clientPlaybackNonce,B5(this.B),this.A&&this.lh()):(this.J=!0,this.A&&G5(this)&&(2==a?A5(this.B):3==a&&C5(this.B)))};
g.h.zQ=function(a){if(a){for(a=0;a<this.C.length;a++)g.zU(this.K,this.C[a].element,!0);this.eD(1)}else this.H=null,this.J=!1;this.lh()};
g.h.Nv=function(){return this.A&&G5(this)};g.t(I5,g.FU);g.h=I5.prototype;g.h.CC=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!JCa(this.player)||b;a=g.vP(a,"ypc_module");var c=g.H_(this.player.app);return b&&!a&&!c};
g.h.BC=function(){return this.o.Nv()};
g.h.BN=function(){return this.BC()?this.o.FN():!1};
g.h.Y=function(){g.rU(this.player,"endscreen");g.FU.prototype.Y.call(this)};
g.h.load=function(){g.FU.prototype.load.call(this);this.o.show()};
g.h.unload=function(){g.FU.prototype.unload.call(this);this.o.hide();this.o.destroy()};
g.h.BO=function(a){this.CC()&&(this.o.created||this.o.create(),"load"==a.getId()&&this.load())};
g.h.CO=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.DF=function(){g.rU(this.player,"endscreen");var a=Math.max(1E3*(this.player.getVideoData().lengthSeconds-10),0);a=new g.vQ(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.N(this,a);var b=new g.vQ(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.N(this,b);g.nU(this.player,[a,b])};g.CX.endscreen=I5;})(_yt_player);
